add the exhaustive nb hits to be ISO, currently it's always set to false
meilisearch/transplant pull request #115
Opened 2021-03-22 17:43 UTC by irevoire

2021-03-22 17:51 UTC, curquiza commented
@MarinPostma does MeiliSearch (the old one) returns sometimes another value than `false`?

2021-03-22 17:54 UTC, MarinPostma commented
No never

2021-03-22 17:55 UTC, MarinPostma requested changes

2021-03-22 17:55 UTC, MarinPostma commented on meilisearch-http/src/index/search.rs
> +    pub exhaustive_nb_hits: bool, // currently this field only exist to be ISO and is always alse
```suggestion
    pub exhaustive_nb_hits: bool, // currently this field only exist to be ISO and is always false
```

2021-03-22 18:28 UTC, curquiza requested changes

2021-03-22 18:28 UTC, curquiza commented on meilisearch-http/src/index/search.rs
> +            exhaustive_nb_hits: false, // not implemented, we use it to be ISO
```suggestion
            exhaustive_nb_hits: false, // not implemented yet
```

2021-03-22 18:28 UTC, curquiza commented on meilisearch-http/src/index/search.rs
> +            exhaustive_nb_hits: false, // not implemented, we use it to be ISO
We should not talk about being ISO in the code since this code will be merged into MeiliSearch 🙂

2021-03-23 13:10 UTC, curquiza approved these changes

2021-03-23 13:23 UTC, curquiza requested changes
Sorry to ask you this now -> can you add a check in one of the tests to check the field `exhaustiveNbHits` is present in the search response body?

2021-03-23 14:57 UTC, curquiza commented
What do you mean?

I agree we do not need to test the value of exhausitveNbHits 🙂 but in any cases the exhausitveNbHits key should be present in the search response. So testing the key is present could be great

2021-03-23 16:01 UTC, MarinPostma commented
@curquiza, what @irevoire  means is that we haven't started testing search just yet :)

We are waiting for milli to stabilize the search before we get to it.

@irevoire, can you add the tests we have to do to #3 so we don't forget them? :)

2021-03-23 16:46 UTC, MarinPostma commented on meilisearch-http/src/index/search.rs
> +    pub exhaustive_nb_hits: bool, // currently this field only exist to be ISO and is always false
```suggestion
    pub exhaustive_nb_hits: bool,
```

2021-03-23 16:47 UTC, MarinPostma requested changes
One last change, given @curquiza 's last comment

2021-03-23 21:15 UTC, MarinPostma approved these changes
bors merge

2021-03-24 08:34 UTC, curquiza commented
Got it!

2021-03-24 10:53 UTC, curquiza approved these changes

2021-03-24 11:44 UTC, MarinPostma commented
bors merge

2021-03-24 12:16 UTC, curquiza commented
We could not merge with bors because of me (in the settings). I fixed it! Sorry

bors merge

2021-03-24 12:24 UTC, merged