add _formated field to search result
meilisearch/transplant pull request #150
Opened 2021-04-19 17:06 UTC by MarinPostma

close #75

2021-04-20 08:33 UTC, Kerollmops commented on meilisearch-http/src/index/search.rs
> +    #[serde(rename = "_formatted", skip_serializing_if = "Map::is_empty")]
```suggestion
    #[serde(rename = "_formatted", skip_serializing_if = "Document::is_empty")]
```

:)

2021-04-20 08:46 UTC, curquiza requested changes
With this request:
```json
{
    "q": "",
    "attributesToRetrieve": ["title", "author"],
    "attributesToHighlight": ["*"]
}
```

I don't get any `_formatted`:
```json
{
    "hits": [
        {
            "author": "Lewis Carroll",
            "title": "Alice In Wonderland"
        },
        {
            "author": "J. R. R. Tolkien",
            "title": "The Hobbit"
        },
        {
            "author": "Jane Austin",
            "title": "Pride and Prejudice"
        },
        {
            "author": "J. K. Rowling",
            "title": "Harry Potter and the Half-Blood Prince"
        },
        {
            "author": "Douglas Adams",
            "title": "The Hitchhiker's Guide to the Galaxy"
        },
        {
            "author": "Antoine de Saint-Exupéry",
            "title": "Le Petit Prince"
        }
    ],
    "nbHits": 6,
    "exhaustiveNbHits": false,
    "query": "",
    "limit": 20,
    "offset": 0,
    "processingTimeMs": 8
}
```

2021-04-20 12:00 UTC, curquiza requested changes
I found out two problems:
- the order of the attributes changes for each request (in `_formatted` or not)
- the `displayedAttributes` are not taken into account during the search

2021-04-20 13:12 UTC, irevoire approved these changes

2021-04-20 13:14 UTC, irevoire commented
> * the order of the attributes changes for each request (in `_formatted` or not)
Is this really a problem? 
I guess we could use a `BTreeSet` to always return everything in the same order but since we are returning json I don't think we needs to.

2021-04-20 13:28 UTC, irevoire requested changes

2021-04-20 13:28 UTC, irevoire commented on meilisearch-http/src/index/search.rs
> +        let displayed_ids: HashSet<FieldId> = fields_ids_map.iter().map(|(id, _)| id).collect();
```suggestion
        let displayed_ids = sel.fields_to_display(&rtxn, query.attribute_to_retrieve, &fields_ids_map)?;
        let displayed_ids: HashSet<FieldId> = displayed_ids.iter().map(|(id, _)| id).collect();
```

2021-04-20 13:28 UTC, irevoire commented on meilisearch-http/src/index/search.rs
> +        let displayed_ids: HashSet<FieldId> = fields_ids_map.iter().map(|(id, _)| id).collect();
I think this should fix the bug @curquiza found about the `displayedAttributes` not being taken in account during the search

2021-04-20 13:44 UTC, MarinPostma commented
I agree with @irevoire, this is useless imo, but, since we need to do it anyway, we need to use indexmap

2021-04-20 14:01 UTC, curquiza commented
Since we have a criterion where the order of attributes matters, it's important to still return the same order to the user: even if it does not have any impact, it avoids confusion for the users. Until the product team decides the contrary, we need to stay consistent between two searches 🙂

2021-04-20 19:24 UTC, MarinPostma commented
@curquiza both issues are now fixed

2021-04-21 13:58 UTC, curquiza approved these changes
Looks good to meeeeeeee 🚀 
well done!!!

2021-04-21 14:22 UTC, MarinPostma commented
Bors merge

2021-04-21 16:33 UTC, MarinPostma commented
bors merge

2021-04-21 16:43 UTC, merged