optimize cropping
meilisearch/transplant pull request #216
Opened 2021-06-20 15:00 UTC by MarinPostma

Optimize cropping as per @kerollmops suggestion.

2021-06-20 15:34 UTC, curquiza approved these changes
Thanks!!! 😊

2021-06-21 08:59 UTC, Kerollmops requested changes

2021-06-21 08:59 UTC, Kerollmops commented on meilisearch-http/src/index/search.rs
> +                    if format_options.highlight && token.is_word() {
```suggestion
                if format_options.highlight && token.is_word() {
                    if let Some(match_len) = matcher.matches(token.text()) {
```

Calling `matches` is more CPU intensive than checking that the token is a word or that we must highlight it.

2021-06-21 09:59 UTC, Kerollmops approved these changes
Nice change! :)

2021-06-21 10:00 UTC, MarinPostma commented
bors merge

2021-06-21 10:24 UTC, merged