Stop logging the no space left on device error
meilisearch/transplant pull request #246
Opened 2021-06-28 11:29 UTC by irevoire

closes #208
@qdequele what do you think of that?
Are there any other errors we need to ignore?

As you can see in the code, once we are in `Sentry` the error has already been converted to a `String` so the only thing we can do to see if we need to send the error or not is to match the `String` against our error message. 
If we have a lot of other logs we want to ignore I would suggest prefixing all the logs with something like:
```
User error: No space left on device
```
So in Sentry, we could just check if the log start by `User error:` and ignore all these errors at once

2021-06-28 11:38 UTC, Kerollmops requested changes

2021-06-28 11:38 UTC, Kerollmops commented on meilisearch-http/src/main.rs
> +                            .map(|msg| msg.contains("no space left on device"))
```suggestion
                            .map(|msg| msg.to_lowercase().contains("no space left on device"))
```

2021-06-28 15:03 UTC, qdequele commented
It is not possible to not log the "no space left" errors as real errors and log them as traces logs?

2021-06-29 08:13 UTC, irevoire commented
Yes, we could do that, but as a user, that's probably one of the few logs that would really interest me since it stops me from using meilisearch.
In my opinion, this log should say a big red ERROR.

But if it was the only error, you wanted to remove, we can merge this PR as-is and it'll be ok :smile:

2021-06-29 08:19 UTC, curquiza commented
I agree with @irevoire. Plus, the error of "no space left on the device" on windows should not be present anymore 🤞
If it's still really annoying @qdequele, let us know once the v0.21 is out!

2021-06-29 08:20 UTC, curquiza approved these changes
thanks @irevoire!

bors merge

2021-06-29 08:41 UTC, merged